### ISSUE TITLE
odds.py - TypeError: string indices must be integers

### ISSUE THREAD

**Issue by hanikhatib** [jrey999/mlb-positive-ev#1]
When I reach the command: python odds.py

I get the following error:

Traceback (most recent call last):
  File "/Users/mlb-positive-ev/odds.py", line 8, in <module>
    game = Game(game)
  File "/Users/mlb-positive-ev/odds/datamodels.py", line 10, in __init__
    self.data = game_and_odds["bookmakers"]
TypeError: string indices must be integers

Have you ran into this before? If so, any help here would be much appreciated. Working off a Macbook M1.
Thanks.

**Comment by jrey999** [comment]
double check that you created an API KEY from https://the-odds-api.com/

and that you created a .env file that has API_KEY=###your API Key Here###

That error is likely because when a request was made to the odds-api, it wasn't authenticated with an API key, so instead of returning data it returned
```{'message': 'API key is missing'}```

**Comment by hanikhatib** [comment]
Thanks for the quick response. I re-cloned the repo and made sure the API key was authenticated. it works now! Thanks

**Comment by jrey999** [comment]
Glad to hear
